# Generated by Django 3.2.7 on 2021-10-07 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='images/rooms')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='images/rooms')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='images/rooms')),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(0, 'AVAILABLE'), (1, 'OCCUPIED'), (2, 'UNDER_MAINTENANCE'), (3, 'UNAVAILABLE')], default=0)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(0, 'STANDARD'), (1, 'ECONOMY'), (2, 'PREMIUM'), (3, 'SUITE')], default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('booked_for', models.DateTimeField(blank=True, null=True)),
                ('booked_for_days', models.IntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
