# Generated by Django 3.2.7 on 2021-10-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED'), (2, 'ACCOMMODATED'), (3, 'CANCELLED')], default=0),
        ),
    ]
