# Generated by Django 3.2.7 on 2021-10-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_for',
            new_name='booked_from',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
