# Generated by Django 3.2.7 on 2021-09-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_user',
            new_name='is_staff',
        ),
    ]
